=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenFga
  class AuthErrorCode
    NO_AUTH_ERROR = "no_auth_error".freeze
    AUTH_FAILED_INVALID_SUBJECT = "auth_failed_invalid_subject".freeze
    AUTH_FAILED_INVALID_AUDIENCE = "auth_failed_invalid_audience".freeze
    AUTH_FAILED_INVALID_ISSUER = "auth_failed_invalid_issuer".freeze
    INVALID_CLAIMS = "invalid_claims".freeze
    AUTH_FAILED_INVALID_BEARER_TOKEN = "auth_failed_invalid_bearer_token".freeze
    BEARER_TOKEN_MISSING = "bearer_token_missing".freeze
    UNAUTHENTICATED = "unauthenticated".freeze
    FORBIDDEN = "forbidden".freeze

    def self.all_vars
      @all_vars ||= [NO_AUTH_ERROR, AUTH_FAILED_INVALID_SUBJECT, AUTH_FAILED_INVALID_AUDIENCE, AUTH_FAILED_INVALID_ISSUER, INVALID_CLAIMS, AUTH_FAILED_INVALID_BEARER_TOKEN, BEARER_TOKEN_MISSING, UNAUTHENTICATED, FORBIDDEN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AuthErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AuthErrorCode"
    end
  end
end
