=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0


=end

require 'date'
require 'time'

module OpenFga
  class ListUsersRequest < ApiModelBase
    attr_accessor :object

    attr_accessor :relation

    # The type of results returned. Only accepts exactly one value.
    attr_accessor :user_filters

    attr_accessor :authorization_model_id

    attr_accessor :contextual_tuples

    # Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation.
    attr_accessor :context

    attr_accessor :consistency

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'object': :'object',
        'relation': :'relation',
        'user_filters': :'user_filters',
        'authorization_model_id': :'authorization_model_id',
        'contextual_tuples': :'contextual_tuples',
        'context': :'context',
        'consistency': :'consistency'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'object': :'FgaObject',
        'relation': :'String',
        'user_filters': :'Array<UserTypeFilter>',
        'authorization_model_id': :'String',
        'contextual_tuples': :'Array<TupleKey>',
        'context': :'Object',
        'consistency': :'ConsistencyPreference'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, 'The input argument (attributes) must be a hash in `OpenFga::ListUsersRequest` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenFga::ListUsersRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = nil
      end

      if attributes.key?(:'relation')
        self.relation = attributes[:'relation']
      else
        self.relation = nil
      end

      if attributes.key?(:'user_filters')
        if (value = attributes[:'user_filters']).is_a?(Array)
          self.user_filters = value
        end
      else
        self.user_filters = nil
      end

      if attributes.key?(:'authorization_model_id')
        self.authorization_model_id = attributes[:'authorization_model_id']
      end

      if attributes.key?(:'contextual_tuples')
        if (value = attributes[:'contextual_tuples']).is_a?(Array)
          self.contextual_tuples = value
        end
      end

      if attributes.key?(:'context')
        self.context = attributes[:'context']
      end

      if attributes.key?(:'consistency')
        self.consistency = attributes[:'consistency']
      else
        self.consistency = 'UNSPECIFIED'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @object.nil?
        invalid_properties.push('invalid value for "object", object cannot be nil.')
      end

      if @relation.nil?
        invalid_properties.push('invalid value for "relation", relation cannot be nil.')
      end

      if @user_filters.nil?
        invalid_properties.push('invalid value for "user_filters", user_filters cannot be nil.')
      end

      if @user_filters.length > 1
        invalid_properties.push('invalid value for "user_filters", number of items must be less than or equal to 1.')
      end

      if @user_filters.length < 1
        invalid_properties.push('invalid value for "user_filters", number of items must be greater than or equal to 1.')
      end

      if !@contextual_tuples.nil? && @contextual_tuples.length > 100
        invalid_properties.push('invalid value for "contextual_tuples", number of items must be less than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @object.nil?
      return false if @relation.nil?
      return false if @user_filters.nil?
      return false if @user_filters.length > 1
      return false if @user_filters.length < 1
      return false if !@contextual_tuples.nil? && @contextual_tuples.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] object Value to be assigned
    def object=(object)
      if object.nil?
        fail ArgumentError, 'object cannot be nil'
      end

      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] relation Value to be assigned
    def relation=(relation)
      if relation.nil?
        fail ArgumentError, 'relation cannot be nil'
      end

      @relation = relation
    end

    # Custom attribute writer method with validation
    # @param [Object] user_filters Value to be assigned
    def user_filters=(user_filters)
      if user_filters.nil?
        fail ArgumentError, 'user_filters cannot be nil'
      end

      if user_filters.length > 1
        fail ArgumentError, 'invalid value for "user_filters", number of items must be less than or equal to 1.'
      end

      if user_filters.length < 1
        fail ArgumentError, 'invalid value for "user_filters", number of items must be greater than or equal to 1.'
      end

      @user_filters = user_filters
    end

    # Custom attribute writer method with validation
    # @param [Object] contextual_tuples Value to be assigned
    def contextual_tuples=(contextual_tuples)
      if contextual_tuples.nil?
        fail ArgumentError, 'contextual_tuples cannot be nil'
      end

      if contextual_tuples.length > 100
        fail ArgumentError, 'invalid value for "contextual_tuples", number of items must be less than or equal to 100.'
      end

      @contextual_tuples = contextual_tuples
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          object == o.object &&
          relation == o.relation &&
          user_filters == o.user_filters &&
          authorization_model_id == o.authorization_model_id &&
          contextual_tuples == o.contextual_tuples &&
          context == o.context &&
          consistency == o.consistency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [object, relation, user_filters, authorization_model_id, contextual_tuples, context, consistency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
