=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0


=end

require 'date'
require 'time'

module OpenFga
  class WriteRequestWrites < ApiModelBase
    attr_accessor :tuple_keys

    # On 'error' ( or unspecified ), the API returns an error if an identical tuple already exists. On 'ignore', identical writes are treated as no-ops (matching on user, relation, object, and RelationshipCondition).
    attr_accessor :on_duplicate

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'tuple_keys': :'tuple_keys',
        'on_duplicate': :'on_duplicate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'tuple_keys': :'Array<TupleKey>',
        'on_duplicate': :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, 'The input argument (attributes) must be a hash in `OpenFga::WriteRequestWrites` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenFga::WriteRequestWrites`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tuple_keys')
        if (value = attributes[:'tuple_keys']).is_a?(Array)
          self.tuple_keys = value
        end
      else
        self.tuple_keys = nil
      end

      if attributes.key?(:'on_duplicate')
        self.on_duplicate = attributes[:'on_duplicate']
      else
        self.on_duplicate = 'error'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @tuple_keys.nil?
        invalid_properties.push('invalid value for "tuple_keys", tuple_keys cannot be nil.')
      end

      if @tuple_keys.length < 1
        invalid_properties.push('invalid value for "tuple_keys", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @tuple_keys.nil?
      return false if @tuple_keys.length < 1
      on_duplicate_validator = EnumAttributeValidator.new('String', ['error', 'ignore'])
      return false unless on_duplicate_validator.valid?(@on_duplicate)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tuple_keys Value to be assigned
    def tuple_keys=(tuple_keys)
      if tuple_keys.nil?
        fail ArgumentError, 'tuple_keys cannot be nil'
      end

      if tuple_keys.length < 1
        fail ArgumentError, 'invalid value for "tuple_keys", number of items must be greater than or equal to 1.'
      end

      @tuple_keys = tuple_keys
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] on_duplicate Object to be assigned
    def on_duplicate=(on_duplicate)
      validator = EnumAttributeValidator.new('String', ['error', 'ignore'])
      unless validator.valid?(on_duplicate)
        fail ArgumentError, "invalid value for \"on_duplicate\", must be one of #{validator.allowable_values}."
      end
      @on_duplicate = on_duplicate
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tuple_keys == o.tuple_keys &&
          on_duplicate == o.on_duplicate
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tuple_keys, on_duplicate].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
