=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ConsistencyPreference
    UNSPECIFIED = "UNSPECIFIED".freeze
    MINIMIZE_LATENCY = "MINIMIZE_LATENCY".freeze
    HIGHER_CONSISTENCY = "HIGHER_CONSISTENCY".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, MINIMIZE_LATENCY, HIGHER_CONSISTENCY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ConsistencyPreference.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ConsistencyPreference"
    end
  end
end
