=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class InternalErrorCode
    NO_INTERNAL_ERROR = "no_internal_error".freeze
    INTERNAL_ERROR = "internal_error".freeze
    CANCELLED = "cancelled".freeze
    DEADLINE_EXCEEDED = "deadline_exceeded".freeze
    ALREADY_EXISTS = "already_exists".freeze
    RESOURCE_EXHAUSTED = "resource_exhausted".freeze
    FAILED_PRECONDITION = "failed_precondition".freeze
    ABORTED = "aborted".freeze
    OUT_OF_RANGE = "out_of_range".freeze
    UNAVAILABLE = "unavailable".freeze
    DATA_LOSS = "data_loss".freeze

    def self.all_vars
      @all_vars ||= [NO_INTERNAL_ERROR, INTERNAL_ERROR, CANCELLED, DEADLINE_EXCEEDED, ALREADY_EXISTS, RESOURCE_EXHAUSTED, FAILED_PRECONDITION, ABORTED, OUT_OF_RANGE, UNAVAILABLE, DATA_LOSS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if InternalErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #InternalErrorCode"
    end
  end
end
