=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class NotFoundErrorCode
    NO_NOT_FOUND_ERROR = "no_not_found_error".freeze
    UNDEFINED_ENDPOINT = "undefined_endpoint".freeze
    STORE_ID_NOT_FOUND = "store_id_not_found".freeze
    UNIMPLEMENTED = "unimplemented".freeze

    def self.all_vars
      @all_vars ||= [NO_NOT_FOUND_ERROR, UNDEFINED_ENDPOINT, STORE_ID_NOT_FOUND, UNIMPLEMENTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if NotFoundErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #NotFoundErrorCode"
    end
  end
end
