=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TypeName
    UNSPECIFIED = "TYPE_NAME_UNSPECIFIED".freeze
    ANY = "TYPE_NAME_ANY".freeze
    BOOL = "TYPE_NAME_BOOL".freeze
    STRING = "TYPE_NAME_STRING".freeze
    INT = "TYPE_NAME_INT".freeze
    UINT = "TYPE_NAME_UINT".freeze
    DOUBLE = "TYPE_NAME_DOUBLE".freeze
    DURATION = "TYPE_NAME_DURATION".freeze
    TIMESTAMP = "TYPE_NAME_TIMESTAMP".freeze
    MAP = "TYPE_NAME_MAP".freeze
    LIST = "TYPE_NAME_LIST".freeze
    IPADDRESS = "TYPE_NAME_IPADDRESS".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, ANY, BOOL, STRING, INT, UINT, DOUBLE, DURATION, TIMESTAMP, MAP, LIST, IPADDRESS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TypeName.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TypeName"
    end
  end
end
