# -*- encoding: utf-8 -*-

=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "openfga/version"

Gem::Specification.new do |s|
  s.name        = "openfga"
  s.version     = OpenFga::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenFGA"]
  s.email       = ["contact@openfga.dev"]
  s.homepage    = "https://openfga.dev"
  s.summary     = "This is an autogenerated ruby SDK for OpenFGA. It provides a wrapper around the [OpenFGA API definition](https://openfga.dev/api)."
  s.description = "A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">=3.2"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? && !f.match(/.gem/) }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
