=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenFga::Nodes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenFga::Nodes do
  let(:instance) { OpenFga::Nodes.new }

  describe 'test an instance of Nodes' do
    it 'should create an instance of Nodes' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenFga::Nodes)
    end
  end

  describe 'test attribute "nodes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
