=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TypeName
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TypeName do
  let(:instance) { OpenapiClient::TypeName.new }

  describe 'test an instance of TypeName' do
    it 'should create an instance of TypeName' do
      expect(instance).to be_instance_of(OpenapiClient::TypeName)
    end
  end
end
