=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 6.4.0


=end

# Common files
require 'openfga/constants'
require 'openfga/api_client'
require 'openfga/api_error'
require 'openfga/api_model_base'
require 'openfga/version'
require 'openfga/configuration'

require 'openfga/imports'

# Models
require 'openfga/models/aborted_message_response'
require 'openfga/models/any'
require 'openfga/models/assertion'
require 'openfga/models/assertion_tuple_key'
require 'openfga/models/auth_error_code'
require 'openfga/models/authorization_model'
require 'openfga/models/batch_check_item'
require 'openfga/models/batch_check_request'
require 'openfga/models/batch_check_response'
require 'openfga/models/batch_check_single_result'
require 'openfga/models/check_error'
require 'openfga/models/check_request'
require 'openfga/models/check_request_tuple_key'
require 'openfga/models/check_response'
require 'openfga/models/computed'
require 'openfga/models/condition'
require 'openfga/models/condition_metadata'
require 'openfga/models/condition_param_type_ref'
require 'openfga/models/consistency_preference'
require 'openfga/models/contextual_tuple_keys'
require 'openfga/models/create_store_request'
require 'openfga/models/create_store_response'
require 'openfga/models/difference'
require 'openfga/models/error_code'
require 'openfga/models/expand_request'
require 'openfga/models/expand_request_tuple_key'
require 'openfga/models/expand_response'
require 'openfga/models/fga_object'
require 'openfga/models/forbidden_response'
require 'openfga/models/get_store_response'
require 'openfga/models/internal_error_code'
require 'openfga/models/internal_error_message_response'
require 'openfga/models/leaf'
require 'openfga/models/list_objects_request'
require 'openfga/models/list_objects_response'
require 'openfga/models/list_stores_response'
require 'openfga/models/list_users_request'
require 'openfga/models/list_users_response'
require 'openfga/models/metadata'
require 'openfga/models/node'
require 'openfga/models/nodes'
require 'openfga/models/not_found_error_code'
require 'openfga/models/null_value'
require 'openfga/models/object_relation'
require 'openfga/models/path_unknown_error_message_response'
require 'openfga/models/read_assertions_response'
require 'openfga/models/read_authorization_model_response'
require 'openfga/models/read_authorization_models_response'
require 'openfga/models/read_changes_response'
require 'openfga/models/read_request'
require 'openfga/models/read_request_tuple_key'
require 'openfga/models/read_response'
require 'openfga/models/relation_metadata'
require 'openfga/models/relation_reference'
require 'openfga/models/relationship_condition'
require 'openfga/models/source_info'
require 'openfga/models/status'
require 'openfga/models/store'
require 'openfga/models/tuple'
require 'openfga/models/tuple_change'
require 'openfga/models/tuple_key'
require 'openfga/models/tuple_key_without_condition'
require 'openfga/models/tuple_operation'
require 'openfga/models/tuple_to_userset'
require 'openfga/models/type_definition'
require 'openfga/models/type_name'
require 'openfga/models/typed_wildcard'
require 'openfga/models/unauthenticated_response'
require 'openfga/models/unprocessable_content_error_code'
require 'openfga/models/unprocessable_content_message_response'
require 'openfga/models/user'
require 'openfga/models/user_type_filter'
require 'openfga/models/users'
require 'openfga/models/userset'
require 'openfga/models/userset_tree'
require 'openfga/models/userset_tree_difference'
require 'openfga/models/userset_tree_tuple_to_userset'
require 'openfga/models/userset_user'
require 'openfga/models/usersets'
require 'openfga/models/validation_error_message_response'
require 'openfga/models/write_assertions_request'
require 'openfga/models/write_authorization_model_request'
require 'openfga/models/write_authorization_model_response'
require 'openfga/models/write_request'
require 'openfga/models/write_request_deletes'
require 'openfga/models/write_request_writes'

# APIs
require 'openfga/api/open_fga_api'

module OpenFga
  class << self
    # Customize default settings for the SDK using block.
    #   OpenFga.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
